### ISSUE TITLE
Easy migrate?

### ISSUE THREAD

**Issue by Eik-S** [tracemap/tracemap-crawlers#1]
Thanks for your effort in creating the project.
The main project exists under https://github.com/Eik-S/TraceMap

Also we have few followers on the project, therefore i dont know if we should migrate it now or is there some clever way?
What are the advantages of the organization?

**Comment by Bacis** [comment]
The most important thing is listing all the new projects under this url: https://github.com/tracemap, as I understood there will be at least two new github repos for the project which is the crawler and the web application for the users. It's just a nice and tidy way of having everything in one place. Also there's a nice way here of managing and building teams and giving them certain permissions, might be useful for the growth in the future! I don't see some many followers, perhaps we can transfer them contacting them privately?
